ServerEvents.recipes(event => {
    //Maceration
    const rocksToCrush = [
        'create:limestone',
        'undergarden:depthrock',
        'undergarden:shiverstone',
        'ad_astra:moon_stone',
        'ad_astra:venus_stone',
        'ad_astra:mercury_stone',
        'ad_astra:mars_stone',
        'ad_astra:glacio_stone'
    ]
    rocksToCrush.forEach(rock => {
        var rockName = rock.replace(/create:|undergarden:|ad_astra:/, "")
        event.recipes.gtceu.macerator(`${rockName}_macerator`)
        .itemInputs(rock)
        .itemOutputs(`gtceu:${rockName}_dust`)
        .duration(214)
        .EUt(2)
    })
    //Centrifuging
    event.recipes.gtceu.centrifuge('depthrock_centrifuge')
        .itemInputs('1x #forge:dusts/depthrock')
        .chancedOutput('1x undergarden:sediment', 9000, 300)
        .chancedOutput('1x gtceu:phosphate_dust', 860, 220)
        .chancedOutput('1x gtceu:carbon_dust', 200, 50)
        .outputFluids(Fluid.of('gtceu:sulfuric_gas', 50))
        .duration(160)
        .EUt(GTValues.V[GTValues.HV])
    event.recipes.gtceu.centrifuge('shiverstone_centrifuge')
        .itemInputs('1x #forge:dusts/shiverstone')
        .chancedOutput('1x undergarden:sediment', 9000, 300)
        .chancedOutput('1x gtceu:electrotine_dust', 860, 220)
        .chancedOutput('1x gtceu:carbon_dust', 200, 50)
        .outputFluids(Fluid.of('gtceu:nitrous_oxide', 50))
        .duration(160)
        .EUt(GTValues.V[GTValues.EV])
    event.recipes.gtceu.centrifuge('sediment_centrifuge')
        .itemInputs('1x undergarden:sediment')
        .chancedOutput('1x minecraft:soul_sand', 9000, 300)
        .chancedOutput('1x gtceu:sulfur_dust', 860, 220)
        .chancedOutput('1x gtceu:carbon_dust', 200, 50)
        .outputFluids(Fluid.of('gtceu:oil_heavy', 50))
        .duration(160)
        .EUt(GTValues.V[GTValues.EV])
    event.recipes.gtceu.centrifuge('moon_stone_centrifuge')
        .itemInputs('1x #forge:dusts/moon_stone')
        .chancedOutput('1x ad_astra:moon_sand', 9000, 300)
        .chancedOutput('1x gtceu:aluminium_dust', 860, 220)
        .chancedOutput('1x gtceu:rutile_dust', 200, 50)
        .outputFluids(Fluid.of('gtceu:helium_3', 50))
        .duration(160)
        .EUt(480)
    event.recipes.gtceu.centrifuge('mars_stone_centrifuge')
        .itemInputs('1x #forge:dusts/mars_stone')
        .chancedOutput('1x ad_astra:mars_sand', 9000, 300)
        .chancedOutput('1x gtceu:hematite_dust', 2250, 250)
        .chancedOutput('1x gtceu:tiny_demonite_dust', 460, 120)
        .chancedOutput('1x gtceu:ice_dust', 50, 150)
        .duration(200)
        .EUt(1920)
    event.recipes.gtceu.centrifuge('venus_stone_centrifuge')
        .itemInputs('1x #forge:dusts/venus_stone')
        .chancedOutput('1x ad_astra:venus_sand', 9000, 300)
        .chancedOutput('1x gtceu:selenium_dust', 1820, 220)
        .chancedOutput('1x gtceu:tiny_redstone_dust', 340, 100)
        .outputFluids(Fluid.of('gtceu:sulfur_trioxide', 50))
        .duration(240)
        .EUt(1920)
    event.recipes.gtceu.centrifuge('mercury_stone_centrifuge')
        .itemInputs('1x #forge:dusts/mercury_stone')
        .chancedOutput('1x spawn:blasted_sand', 9000, 300)
        .chancedOutput('1x minecraft:blaze_powder', 5940, 280)
        .chancedOutput('1x gtceu:naquadah_dust', 1010, 160)
        .chancedOutput('1x gtceu:enriched_naquadah_dust', 100, 40)
        .chancedOutput('1x gtceu:small_plutonium_dust', 90, 30)
        .duration(280)
        .EUt(1920)
    event.recipes.gtceu.centrifuge('glacio_stone_centrifuge')
        .itemInputs('1x #forge:dusts/glacio_stone')
        .chancedOutput('1x undergarden:raw_froststeel', 6500, 300)
        .chancedOutput('1x gtceu:naquadria_dust', 650, 80)
        .chancedOutput('1x gtceu:tiny_neutronium_dust', 80, 20)
        .outputFluids(Fluid.of('gtceu:glacio_atmosphere', 50))
        .duration(380)
        .EUt(GTValues.V[GTValues.LuV])
})