const oresToGrindIE = [
    //overworld, twiforest, nether, aether, starlight, undergarden, with some "OP" ores omitted
    'chalcopyrite',
    'iron',
    'pyrite',
    'copper',
    'graphite',
    'diamond',
    'coal',
    'lazurite',
    'sodalite',
    'lapis',
    'calcite',
    'grossular',
    'spessartine',
    'pyrolusite',
    'tantalite',
    'kyanite',
    'mica',
    'bauxite',
    'pollucite',
    'bentonite',
    'magnetite',
    'olivine',
    'glauconite_sand',
    'redstone',
    'ruby',
    'cinnabar',
    'almandine',
    'pyrope',
    'sapphire',
    'green_sapphire',
    'jade',
    'brilliance',
    'quartzite',
    'chromite',
    'soulstone',
    'vinteum',
    'inert_crystal',
    'mithril',
    'cthonic_gold',
    'gold',
    'electrum',
    'galena',
    'silver',
    'platinum',
    'nickel',
    'sal_ammoniac',
    'spinel',
    'red_garnet',
    'yellow_garnet',
    'tetrahedrite',
    'brass',
    'malachite',
    'turquoise',
    'apatite',
    'tricalcium_phosphate',
    'pyrochlore',
    'tin',
    'cassiterite',
    'cassiterite_sand',
    'zeolite',
    'realgar',
    'lead',
    'garnet_sand',
    'asbestos',
    'diatomite',
    'amethyst',
    'opal',
    'goethite',
    'yellow_limonite',
    'hematite',
    'magnetite',
    'vanadium_magnetite',
    'basaltic_mineral_sand',
    'granitic_mineral_sand',
    'fullers_earth',
    'gypsum',
    'rock_salt',
    'salt',
    'lepidolite',
    'spodumene',
    'oilsands',
    'talc',
    'soapstone',
    'pentlandite',
    'emerald',
    'certus_quartz',
    'barite',
    'alunite',
    'blue_topaz',
    'topaz',
    'chalcocite',
    'bornite',
    'electrotine',
    'dark',
    'saltpeter',
    'sphalerite',
    'blazing_quartz',
    'beryllium',
    'cobaltite',
    'stibnite',
    'garnierite',
    'sulfur',
    'ember',
    'vehement_coal',
    'anthralite',
    'iesnium',
    'zanite',
    'trona',
    'aluminium',
    'skyjade',
    'gravitite',
    'source',
    'scheelite',
    'malarite',
    'deepsilver',
    'molybdenum',
    'starlit_diamond',
    'wulfenite',
    'molybdenite',
    'cloggrum',
    'froststeel',
    'utherium',
    'regalium'
]

/* ServerEvents.recipes(event =>{
    event.forEachRecipe({ type: "gtceu:macerator" }, x => {
        let recipe = JSON.parse(x.json)
        if (recipe.category === 'gtceu:ore_crushing') {
            const input = recipe.itemInputs;
            const outputs = recipe.itemOutputs;
            if (!inputs || !outputs || inputs.length !== 1) return;
            if (!input?.ingredient?.tag) return;
            const oreTagSplit = input.ingredient.tag.split('/');
            if (oreTagSplit[0] === 'forge:raw_materials' && !blacklist.includes(oreTagSplit[1])) {
                const mainOutput = outputs[0].content;
                event.recipe.immersiveengineering.crusher(
                    `${mainOutput.count}x ${mainOutput.ingredient.item}`,
                    `1x #${input.ingredient.tag}`
                )
            }
        }
    })
}) */