ServerEvents.recipes(event => {
    event.recipes.gtceu.mixer("kubejs:dark_steel_dust")
        .itemInputs("#forge:dusts/steel", "#forge:dusts/obsidian", "evilcraft:dark_gem_crushed")
        .itemOutputs("gtceu:dark_steel_dust")
        .duration(80)
        .EUt(15)
    
    event.recipes.gtceu.mixer("kubejs:conductive_alloy_dust")
        .itemInputs("#forge:dusts/iron", "#forge:dusts/redstone")
        .itemOutputs("gtceu:conductive_alloy_dust")
        .duration(40)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:pulsating_alloy_dust")
        .itemInputs("#forge:dusts/gallium", "#forge:dusts/ender_pearl", "#forge:dusts/manasteel")
        .itemOutputs("gtceu:pulsating_alloy_dust")
        .duration(40)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:vibrant_alloy_dust")
        .itemInputs("#forge:dusts/energetic_alloy", "#forge:dusts/ender_pearl", "#forge:dusts/luminite")
        .itemOutputs("gtceu:vibrant_alloy_dust")
        .duration(260)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:electrical_steel_dust")
        .itemInputs("#forge:dusts/steel", "#forge:dusts/silicon", "#forge:dusts/regalium")
        .itemOutputs("gtceu:electrical_steel_dust")
        .duration(260)
        .EUt(30)

    event.recipes.gtceu.mixer("kubejs:energetic_alloy_dust")
        .itemInputs("#forge:dusts/gold", "#forge:dusts/redstone", "#forge:dusts/glowstone", "#forge:dusts/electrotine")
        .itemOutputs("2x gtceu:energetic_alloy_dust")
        .duration(140)
        .EUt(30)
    
    event.recipes.gtceu.alloy_blast_smelter("kubejs:soularium")
        .itemInputs("#forge:dusts/iesnium", "#forge:dusts/gold", "16x #forge:ground/soul", "8x gtceu:raw_will_dust")
        .outputFluids(Fluid.of("gtceu:soularium", 288))
        .duration(112.5 * 20 * 9 * 0.75 + 12.5)
        .EUt(120)
        .blastFurnaceTemp(1200)
    
    event.recipes.gtceu.alloy_blast_smelter("kubejs:end_steel")
        .itemInputs("#forge:dusts/dark_steel", "#forge:dusts/endstone", "#forge:dusts/vibrant_alloy", "#forge:dusts/aeternium")
        .outputFluids(Fluid.of("gtceu:end_steel", 288))
        .duration(112.5 * 20 * 9 * 0.75 + 12.5)
        .EUt(120)
        .blastFurnaceTemp(1200)
})