ServerEvents.recipes(event => {
     let brazier_summoning = (mob, count, input1, input2, focus, reagent) => {
    event.custom({
      "type": "eidolon:ritual_brazier_summoning",
      "focusItems": [],
      "output": {
        "count": count,
        "entity": mob
      },
      "pedestalItems": [
        {
          "item": focus
        },
        {
          "item": input1
        },
        {
          "item": input2
        },
      ],
      "reagent": [
        {
          "item": reagent
        }
      ]
    })
  }
  //Vanilla
  brazier_summoning(
    'minecraft:witch',
    1,
    'minecraft:glass_bottle',
    'minecraft:redstone',
    'minecraft:nether_wart',
    'minecraft:glowstone_dust'
  )
  brazier_summoning(
    'minecraft:squid',
    2,
    'minecraft:kelp',
    'minecraft:dried_kelp',
    'gtceu:salt_dust',
    'minecraft:black_dye'
  )
  brazier_summoning(
    'minecraft:glow_squid',
    2,
    'minecraft:kelp',
    'minecraft:deepslate',
    'gtceu:salt_dust',
    'minecraft:glowstone_dust'
  )
  brazier_summoning(
    'minecraft:slime',
    2,
    'create:dough',
    'minecraft:lime_dye',
    'minecraft:rotten_flesh',
    'minecraft:moss'
  )
  brazier_summoning(
    'minecraft:magma_cube',
    2,
    'create:dough',
    'minecraft:orange_dye',
    'minecraft:spider_eye',
    'eidolon:crimson_essence'
  )
  brazier_summoning(
    'minecraft:warden',
    1,
    'eidolon:lesser_soul_gem',
    'minecraft:echo_shard',
    'occultism:iesnium_ingot',
    'dungeonsdelight:wardenzola_crumbles'
  )
  brazier_summoning(
    'minecraft:ghast',
    1,
    'eidolon:lesser_soul_gem',
    'mynethersdelight:ghast_sourdough',
    'minecraft:ghast_tear',
    'gtceu:silver_dust'
  )
  brazier_summoning(
    'minecraft:blaze',
    2,
    'botania:fel_pumpkin',
    'minecraft:blaze_powder',
    'embers:ash',
    'malum:infernal_spirit',
  )
  brazier_summoning(
    'minecraft:enderman',
    1,
    'eidolon:lesser_soul_gem',
    'eidolon:ender_calx',
    'minecraft:end_stone',
    'malum:eldritch_spirit'
  )
  brazier_summoning(
    'minecraft:shulker',
    1,
    'eidolon:lesser_soul_gem',
    'eidolon:ender_calx',
    'minecraft:purpur_block',
    'minecraft:shulker_shell'
  )
  //Eidolon
  brazier_summoning(
    'eidolon:zombie_brute',
    1,
    'eidolon:lesser_soul_gem',
    'malum:living_flesh',
    'goety:grave_dust',
    'caverns_and_chasms:rotten_flesh_block'
  )
  //Goety
  brazier_summoning(
    'goety:wraith',
    3,
    'eidolon:soul_shard',
    'hexalia:ghost_powder',
    'hexalia:spirit_powder',
    'malum:wicked_spirit'
  )
  brazier_summoning(
    'goety:reaper',
    1,
    'eidolon:lesser_soul_gem',
    'goety:cursed_ingot',
    'goety:ectoplasm',
    'malum:astral_weave'
  )
  //Abnormals'
  brazier_summoning(
    'autumnity:snail',
    3,
    'minecraft:slimeball',
    'neapolitan:chocolate_bar',
    'minecraft:gold_nugget',
    'spawn:shell_fragments'
  )
  //Alex's Mobs
  brazier_summoning(
    'alexsmobs:bald_eagle',
    3,
    'minecraft:egg',
    'minecraft:feather',
    'malum:aerial_spirit',
    'minecraft:spider_eye'
  )
  brazier_summoning(
    'alexsmobs:alligator_snapping_turtle',
    1,
    'eidolon:soul_shard',
    'eidolon:pewter_ingot',
    'minecraft:dried_kelp_block',
    'minecraft:scute'
  )
  brazier_summoning(
    'alexsmobs:grizzly_bear',
    1,
    'minecraft:honeycomb',
    'minecraft:salmon',
    'minecraft:brown_wool',
    'hexerei:mandrake_root'
  )
  brazier_summoning(
    'alexsmobs:dropbear',
    2,
    'alexsmobs:bear_fur',
    'minecraft:coal',
    'minecraft:smooth_basalt',
    'eidolon:crimson_essence'
  )
  brazier_summoning(
    'alexsmobs:fly',
    3,
    'minecraft:rotten_flesh',
    'minecraft:charcoal',
    'embers:ash',
    'minecraft:string'
  )
  brazier_summoning(
    'alexsmobs:flutter',
    3,
    'minecraft:moss',
    'minecraft:spore_blossom',
    'minecraft:flowering_azalea',
    'minecraft:pink_petals'
  )
})