ServerEvents.recipes(event => {
    let brazier_summoning = (mob, count, input1, input2, focus, reagent) => {
    var identifier = mob.replace(':', '_')
    event.custom({
      "type": "eidolon:ritual_brazier_summoning",
      "focusItems": [
        {
          "item": focus
        }
      ],
      "output": {
        "count": count,
        "entity": mob
      },
      "pedestalItems": [
        {
          "item": input1
        },
        {
          "item": input2
        }
      ],
      "reagent": [
        {
          "item": reagent
        }
      ]
    }).id(`kubejs:eidolon/brazier_summoning/${identifier}`)
  }
  //Vanilla
  brazier_summoning(
    'minecraft:turtle',
    2,
    'minecraft:beef',
    'minecraft:sea_pickle',
    'minecraft:green_dye',
    'minecraft:iron_ingot'
  )
  brazier_summoning(
    'minecraft:chicken',
    3,
    'minecraft:wheat_seeds',
    'minecraft:string',
    'gtceu:calcite_dust',
    'minecraft:apple'
  )
  brazier_summoning(
    'minecraft:cow',
    2,
    'minecraft:hay_block',
    'minecraft:bone_meal',
    'minecraft:bucket',
    'minecraft:rotten_flesh'
  )
  brazier_summoning(
    'minecraft:sheep',
    2,
    'farmersdelight:straw_bale',
    'kubejs:woven_silk',
    'minecraft:shears',
    'minecraft:rotten_flesh'
  )
  brazier_summoning(
    'minecraft:horse',
    1,
    'minecraft:golden_carrot',
    'minecraft:lead',
    'minecraft:feather',
    'kubejs:treated_leather'
  )
  brazier_summoning(
    'minecraft:donkey',
    1,
    'minecraft:golden_carrot',
    'minecraft:lead',
    'minecraft:chest',
    'eidolon:tattered_cloth'
  )
  brazier_summoning(
    'minecraft:llama',
    1,
    'minecraft:mushroom_soup',
    'minecraft:lead',
    'minecraft:tuff',
    'minecraft:white_wool'
  )
  brazier_summoning(
    'minecraft:squid',
    2,
    'minecraft:kelp',
    'minecraft:dried_kelp',
    'gtceu:salt_dust',
    'minecraft:black_dye'
  )
  brazier_summoning(
    'minecraft:glow_squid',
    2,
    'minecraft:kelp',
    'minecraft:deepslate',
    'gtceu:salt_dust',
    'minecraft:glowstone_dust'
  )
  brazier_summoning(
    'minecraft:slime',
    2,
    'farmersdelight:wheat_dough',
    'minecraft:lime_dye',
    'minecraft:rotten_flesh',
    'minecraft:moss_block'
  )
  brazier_summoning(
    'minecraft:magma_cube',
    2,
    'farmersdelight:wheat_dough',
    'minecraft:orange_dye',
    'minecraft:spider_eye',
    'eidolon:crimson_essence'
  )
  brazier_summoning(
    'minecraft:fox',
    2,
    'minecraft:leather',
    'minecraft:orange_dye',
    'minecraft:sweet_berries',
    'kubejs:woven_silk'
  )
  brazier_summoning(
    'minecraft:warden',
    1,
    'eidolon:lesser_soul_gem',
    'minecraft:echo_shard',
    'gtceu:strumm_ingot',
    'dungeonsdelight:wardenzola_crumbles'
  )
  brazier_summoning(
    'minecraft:ghast',
    1,
    'eidolon:lesser_soul_gem',
    'vampiresdelight:rice_dough',
    'minecraft:ghast_tear',
    'gtceu:silver_dust'
  )
  brazier_summoning(
    'minecraft:phantom',
    2,
    'eidolon:lesser_soul_gem',
    'malum:alchemical_calx',
    'kubejs:woven_silk',
    'miners_delight:bat_wing'
  )
  brazier_summoning(
    'minecraft:blaze',
    2,
    'botania:fel_pumpkin',
    'minecraft:blaze_powder',
    'embers:ash',
    'malum:infernal_spirit',
  )
  brazier_summoning(
    'minecraft:enderman',
    1,
    'eidolon:lesser_soul_gem',
    'eidolon:ender_calx',
    'hexcasting:amethyst_dust',
    'malum:eldritch_spirit'
  )
  brazier_summoning(
    'minecraft:shulker',
    1,
    'eidolon:lesser_soul_gem',
    'eidolon:ender_calx',
    'minecraft:purpur_block',
    'minecraft:shulker_shell'
  )
  brazier_summoning(
    'minecraft:bee',
    3,
    'miners_delight:arthropod',
    'gtceu:charcoal_dust',
    'aether:ambrosium_shard',
    'minecraft:sugar'
  )
  brazier_summoning(
    'minecraft:allay',
    3,
    'galosphere:allurite_shard',
    'hexcasting:charged_amethyst',
    'goety:spirit_fabric',
    'hexalia:ghost_powder'
  )
  //Hexalia
  brazier_summoning(
    'hexalia:silk_moth',
    3,
    'miners_delight:arthropod',
    'minecraft:string',
    'hexalia:mutavis',
    'gtceu:stone_dust'
  )
  //Ars Nouveau
  brazier_summoning(
    'ars_nouveau:wilden_hunter',
    3,
    'ars_nouveau:source_gem_block',
    'hexalia:spirit_powder',
    'hexerei:dried_sage',
    'minecraft:bow'
  )
  brazier_summoning(
    'ars_nouveau:wilden_stalker',
    3,
    'ars_nouveau:source_gem_block',
    'malum:astral_weave',
    'hexerei:mandrake_flowers',
    'hexalia:ghost_powder'
  )
  brazier_summoning(
    'ars_nouveau:wilden_guardian',
    3,
    'ars_nouveau:source_gem_block',
    'minecraft:prismarine_shard',
    'hexerei:infused_fabric',
    'hexalia:galeberries'
  )
  brazier_summoning(
    'ars_nouveau:wilden_boss',
    1,
    'twilightforest:hydra_chop',
    'ars_nouveau:wilden_wing',
    'ars_nouveau:wilden_spike',
    'ars_nouveau:wilden_horn'
  )
  //Eidolon
  brazier_summoning(
    'eidolon:zombie_brute',
    1,
    'eidolon:lesser_soul_gem',
    'caverns_and_chasms:living_flesh',
    'goety:grave_dust',
    'minecraft:rotten_flesh'
  )
  /* brazier_summoning(
    'eidolon:giant_skeleton',
    1,
    'eidolon:lesser_soul_gem',
    'reliquary:rib_bone',
    'goety:grave_dust',
    'malum:block_of_grim_talc'
  )*/
  //Goety
  brazier_summoning(
    'goety:wraith',
    3,
    'eidolon:soul_shard',
    'hexalia:ghost_powder',
    'hexalia:spirit_powder',
    'malum:wicked_spirit'
  )
  brazier_summoning(
    'goety:reaper',
    1,
    'eidolon:lesser_soul_gem',
    'goety:cursed_ingot',
    'goety:ectoplasm',
    'malum:astral_weave'
  )
  //Abnormals'
  brazier_summoning(
    'autumnity:snail',
    3,
    'minecraft:slime_ball',
    'neapolitan:chocolate_bar',
    'minecraft:gold_nugget',
    'spawn:shell_fragments'
  )
  //Alex's Mobs
  brazier_summoning(
    'alexsmobs:bald_eagle',
    3,
    'minecraft:egg',
    'minecraft:feather',
    'malum:aerial_spirit',
    'minecraft:spider_eye'
  )
  brazier_summoning(
    'alexsmobs:alligator_snapping_turtle',
    1,
    'eidolon:soul_shard',
    'eidolon:pewter_ingot',
    'minecraft:dried_kelp_block',
    'minecraft:scute'
  )
  brazier_summoning(
    'alexsmobs:grizzly_bear',
    1,
    'minecraft:honeycomb',
    'minecraft:salmon',
    'minecraft:brown_wool',
    'hexerei:mandrake_root'
  )
  brazier_summoning(
    'alexsmobs:komodo_dragon',
    1,
    'eidolon:lesser_soul_gem',
    'twilightforest:naga_scale',
    'malum:earthen_spirit',
    'minecraft:sand'
  )
  brazier_summoning(
    'alexsmobs:dropbear',
    2,
    'alexsmobs:bear_fur',
    'minecraft:coal',
    'minecraft:smooth_basalt',
    'eidolon:crimson_essence'
  )
  brazier_summoning(
    'alexsmobs:fly',
    3,
    'minecraft:rotten_flesh',
    'minecraft:charcoal',
    'embers:ash',
    'minecraft:string'
  )
  brazier_summoning(
    'alexsmobs:flutter',
    3,
    'minecraft:moss_block',
    'minecraft:spore_blossom',
    'minecraft:flowering_azalea',
    'minecraft:pink_petals'
  )
  brazier_summoning(
    'alexsmobs:guster',
    3,
    'quark:bottled_cloud',
    'minecraft:sand',
    'aether:golden_aercloud',
    'malum:aerial_spirit'
  )
  //Cold Sweat
  brazier_summoning(
    'cold_sweat:chameleon',
    2,
    'eidolon:soul_shard',
    'alexsmobs:komodo_spit',
    'minecraft:packed_ice',
    'minecraft:blaze_powder'
  )
})