ServerEvents.recipes(event => {
    function elvenTrade(itemsIn, itemsOut){
           event.recipes.botania.elven_trade(itemsIn, itemsOut)
    }
    elvenTrade(
        [
            'mna:mark_of_the_council',
            'mna:mark_of_the_council',
            'farmersdelight:straw'
        ],
        'mna:cerublossom'
    )
    elvenTrade(
        [
            'mna:mark_of_the_undead',
            'mna:mark_of_the_undead',
            '#forge:flowers'
        ],
        'mna:aum'
    )
    elvenTrade(
        [
            'mna:mark_of_the_undead',
            'mna:mark_of_the_undead',
            'minecraft:dead_bush'
        ],
        'mna:tarma_root'
    )
    elvenTrade(
        [
            'mna:mark_of_the_nether',
            'mna:mark_of_the_nether',
            'minecraft:kelp'
        ],
        'mna:wakebloom'
    )
    elvenTrade(
        [
            'mna:mark_of_the_nether',
            'mna:mark_of_the_nether',
            'minecraft:cactus'
        ],
        'mna:desert_nova'
    )
    elvenTrade(
        [
            '#kubejs:non_fey_marks',
            '#kubejs:non_fey_marks',
            '#kubejs:non_fey_marks'
        ],
        [
            'mna:mark_of_the_fey',
            'mna:mark_of_the_fey',
            'mna:mark_of_the_fey'
        ]
    )
    elvenTrade(
        [
            '#kubejs:non_fey_admixtures',
            '#kubejs:non_fey_admixtures',
            '#kubejs:non_fey_admixtures'
        ],
        [
            'magichem:admixture_fey',
            'magichem:admixture_fey',
            'magichem:admixture_fey'
        ]
    )
    elvenTrade(
        [
            'minecraft:emerald'
        ],
        'minecraft:lapis_lazuli'
    )
    elvenTrade(
        [
            'eidolon:enchanted_ash'
        ],
        'mna:vinteum_dust'
    )
    elvenTrade(
        [
            'malum:grim_talc'
        ],
        'mna:chimerite_block'
    )
    elvenTrade(
        [
            'malum:rotting_essence'
        ],
        'kubejs:lifecrystal' //if you wanna ""skip""" naaura, better rush alfheim
    )
    elvenTrade(
        [
            'embers:ember_shard',
            'eternal_starlight:crinoa'
        ],
        'eternal_starlight:starcore'
    )
})